### ISSUE TITLE
Error when search then playing game.

### ISSUE THREAD

**Issue by tracer8** [sabresaurus/PlayerPrefsEditor#5] opened 2021-02-09 11:09 UTC
Hi,
I'm using search, then playing game. After press play, it is trigger error like bellow:

```
NullReferenceException: Object reference not set to an instance of an object
Sabresaurus.PlayerPrefsEditor.PlayerPrefsEditor.DrawMainList () (at PlayerPrefsEditor.cs:651)
Sabresaurus.PlayerPrefsEditor.PlayerPrefsEditor.OnGUI () (at PlayerPrefsEditor.cs:1117)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <d7545a46516941d4b2f2dec578cd41ee>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <d7545a46516941d4b2f2dec578cd41ee>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <d7545a46516941d4b2f2dec578cd41ee>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <d7545a46516941d4b2f2dec578cd41ee>:0)
UnityEditor.DockArea.OldOnGUI () (at <d7545a46516941d4b2f2dec578cd41ee>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <a9183b39766a483caf86aaa926f3554c>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```
This error occur on all Unity version. And on everytime.
Please check it out, thanks!

**Comment by rfadeev** [comment] 2021-02-09 23:58
Hi,

Could you please provide a bit more information or some sample project for reproduction? Unity version and OS (Windows or macOS) would also be helpful. Reproduction steps may help as well, like do you open prefs editor after game started or is it open before etc.

I just tried latest master branch commit 5aa52c76f0a3da4b00c1fad8a9dcb7f76b4bbf23 on Windows with Unity 2018.4.28f1 and cannot reproduce exception when playing the game. I searched both PlayerPrefs and EditorPrefs.

**Comment by tracer8** [comment] 2021-02-10 04:49
My Unity Version: 2019.4.8f1
My OS: Window 10
Step i made to this exception:
1. I open PlayerPrefsEditor window
2. I search before press play, keep this search
2. Then when i press play.
3. Exception occur.
Even with sample test project, no script, you can search with "unity" keyword, then press play like steps i said above,  this exception will occur too.
Bellow is sample project.
Thanks!
[Sample PlayerPref.zip](https://github.com/sabresaurus/PlayerPrefsEditor/files/5955896/Sample.PlayerPref.zip)

**Comment by rfadeev** [comment] 2021-02-10 21:26
Thank you for the provided details. I managed to reproduce the issue using your sample project. However, I do not fully understand the root cause of it hence not sure how to fix it properly.

From what I understood after debugging, it is caused by `PlayerPrefsEditor.filteredPlayerPrefs` serialization. Note that it is a list which stores items of `PlayerPrefPair` type which is has `Serializable` attribute. Since `PlayerPrefPair.Value` type is `object`, Unity fails to serialize that field when entering playmode. Then later the value is set to null after deserialization once playmode has started. Then you get an exception due to value is `null`.

**Comment by rfadeev** [comment] 2021-02-10 21:46
@sabresaurus Hi, noticed you have self-assigned the issue so decided to check with you. I think I have found a solution and can start preparing pull request.

Pretty much fix is to update `deserializedPlayerPrefs` and `filteredPlayerPrefs` in `PlayerPrefsEditor.OnEnable` like:
```csharp
        private void OnEnable()
        {
            searchField = new SearchField();

            SetDeserializedPrefs();
            UpdateSearch();
        }
```
with `SetDeserializedPrefs` being code extracted from `OnGUI` method.

Approach with implementing `ISerializationCallbackReceiver` and calling those methods there did not work as Unity complains accessing `PlayerSettings.companyName` and `PlayerSettings.productName` during serialization.

I have not yet experimented, but probably this will also allow to remove `Serializable` attribute for `PlayerPrefPair `.

**Comment by sabresaurus** [comment] 2021-02-10 21:50
Hey @rfadeev that's great and makes a lot of sense. I'll reassign the issue to you, thanks for taking a look into it! As you say I can't see a reason to keep it going through the serialisation system if we rebuild it OnEnable()

**Closed as completed** 2021-02-15 22:02 UTC
