### ISSUE TITLE
Can not serialized some variable in editor unity 2021.3.6f1

### ISSUE THREAD

**Issue by vietanhpham-monster** [sabresaurus/PlayerPrefsEditor#10] opened 2022-08-03 07:04 UTC
![image](https://user-images.githubusercontent.com/83327237/182545146-bf4bbeac-c48d-4a72-8253-f7fda7ceeb16.png)
For float variable, it can not show and change value

**Comment by sabresaurus** [comment] 2022-08-06 11:30
Duplicate of #9 please update to 1.4.1

**Closed as completed by sabresaurus** 2022-08-06 11:30 UTC
